[tool.poetry]
name = "hw-21-2"
version = "0.1.0"
description = ""
authors = ["limit3d_PC <itopko@list.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
